

include plat.mak


include mk_opts.mak

include plat_$(PLAT).mak

src1 =

obj1 := $(src1:%.cpp=o/%.$(OEXT))

srcm = bzc.cpp

objm := $(src1:%.cpp=o/%.$(OEXT))

src2 =

obj2 := $(src1:%.cpp=o/%.$(OEXT))

include mk_rules.mak

